apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: demo
  labels:
    app: nginx-service
spec:
  ports:
    - protocol: TCP
      port: 80
  selector:
    app: nginx-service
  type: LoadBalancer
